### ISSUE TITLE
It mustn't work gulp task if an error is encountered in the json file

### ISSUE THREAD

**Issue by mstfsnc** [ysndmr/gulp-render-json#1]
Hi,

The gulp task mustn't work if i have a problem json file. Gulp must have to say/show to me about error message.

**Comment by ysndmr** [comment]
Thanks @mstfsnc. I will do and i will fix that problem. Thanks for your idea and support.

**Comment by ysndmr** [comment]
that issue is fixed @mstfsnc. Thank you.

**Comment by ysndmr** [comment]
that issue is fixed @mstfsnc. Thank you.
